// Auto-generated by GitHub Actions on Thu Nov 13 18:21:22 UTC 2025
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';

// Supabase configuration
const supabaseUrl = 'https://fwpriiugfjhtoymcbmso.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3cHJpaXVnZmpodG95bWNibXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDc3MTgsImV4cCI6MjA3MjQ4MzcxOH0.Sy3iehhGx2UNi28UBEjfNd81TjMxOVXJjY9HJS3xVjs';

// Create and export the Supabase client
export const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: window.localStorage
  }
});

// Flutterwave configuration
const FLUTTERWAVE_PUBLIC_KEY = 'FLWPUBK-0978497ca22822ac346c33118dfd45f4-X';

// Export Flutterwave public key
export const FLWPUBK = FLUTTERWAVE_PUBLIC_KEY;

// Export auth, db, and storage for compatibility with existing code
export const auth = supabase.auth;
export const db = supabase;
export const storage = supabase.storage;
export const messaging = null; // Firebase messaging is not used

console.log('✅ Environment configuration loaded from CI/CD workflow.');
