import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Platform } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '@/constants/colors';
import { useTheme } from '@/context/ThemeContext';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using StatWise, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.`,
  },
  {
    title: '2. Description of Service',
    body: `StatWise provides AI-generated football match predictions for informational and entertainment purposes only. Predictions are generated by machine learning models trained on historical match data and are not guarantees of outcomes.`,
  },
  {
    title: '3. Disclaimer — Not Gambling Advice',
    body: `StatWise does NOT provide gambling or betting advice. All predictions are for entertainment purposes only. We strongly encourage responsible gambling practices. Never bet more than you can afford to lose.\n\nStatWise is not responsible for any financial losses incurred from decisions made based on our predictions.`,
  },
  {
    title: '4. User Accounts',
    body: `You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information and to update it as necessary. You must be at least 18 years old to create an account.`,
  },
  {
    title: '5. Subscription & Payments',
    body: `Subscription fees are charged in Nigerian Naira (NGN) through Flutterwave. All payments are final unless otherwise required by law. Subscriptions grant access to the prediction tier for the selected period (daily or monthly).\n\nStatWise reserves the right to change subscription prices with 7 days notice.`,
  },
  {
    title: '6. Referral Program',
    body: `Referral reward points are issued at our discretion and have no monetary value. We reserve the right to modify or discontinue the referral program at any time. Abuse of the referral system will result in account termination.`,
  },
  {
    title: '7. Intellectual Property',
    body: `All content on StatWise, including predictions, insights, algorithms, and designs, is owned by StatWise and protected by intellectual property laws. You may not reproduce or distribute our content without written permission.`,
  },
  {
    title: '8. Limitation of Liability',
    body: `To the maximum extent permitted by law, StatWise shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount paid by you in the last 30 days.`,
  },
  {
    title: '9. Termination',
    body: `We reserve the right to suspend or terminate accounts that violate these terms, engage in fraudulent activity, or abuse our systems. You may close your account at any time by contacting support.`,
  },
  {
    title: '10. Governing Law',
    body: `These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved in the courts of Nigeria.`,
  },
  {
    title: '11. Contact',
    body: `For questions about these terms, contact us at:\nsupport@statwise.app`,
  },
];

export default function TermsOfServiceScreen() {
  const { scheme } = useTheme();
  const C = Colors[scheme];
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const topInset = Platform.OS === 'web' ? 67 : insets.top;

  return (
    <View style={[styles.container, { backgroundColor: C.background }]}>
      <View style={[styles.header, { paddingTop: topInset + 8, backgroundColor: C.background }]}>
        <TouchableOpacity onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color={C.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: C.text }]}>Terms of Service</Text>
        <View style={{ width: 32 }} />
      </View>

      <ScrollView
        contentContainerStyle={[styles.scroll, { paddingBottom: insets.bottom + 40 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.updated, { color: C.textMuted }]}>Last updated: April 2, 2026</Text>
        <Text style={[styles.intro, { color: C.textSecondary }]}>
          Please read these Terms of Service carefully before using StatWise. These terms govern your use of our AI-powered sports prediction platform.
        </Text>

        {SECTIONS.map((s, i) => (
          <View key={i} style={styles.section}>
            <Text style={[styles.sectionTitle, { color: C.text }]}>{s.title}</Text>
            <Text style={[styles.sectionBody, { color: C.textSecondary }]}>{s.body}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingBottom: 12,
  },
  headerTitle: { fontSize: 18, fontFamily: 'Inter_700Bold' },
  scroll: { paddingHorizontal: 20, paddingTop: 4 },
  updated: { fontSize: 12, fontFamily: 'Inter_400Regular', marginBottom: 16 },
  intro: { fontSize: 15, fontFamily: 'Inter_400Regular', lineHeight: 22, marginBottom: 24 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 16, fontFamily: 'Inter_700Bold', marginBottom: 10 },
  sectionBody: { fontSize: 14, fontFamily: 'Inter_400Regular', lineHeight: 22 },
});
